version: "3.8"

services:
  reportservice:
    # image: mfsinik/report-service:latest
    # container_name: reportservice
    networks:
      - mongo-compass_mongo-network
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.report-service.rule=Host(`report-service.localhost`)"

networks:
  mongo-compass_mongo-network:
    external: true
