version: "3.8"
services:
  reportservice:
    networks:
      - mongo-db_mongo-network
    environment:
      PORT: "8181"
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8181:8181

networks:
  mongo-db_mongo-network:
    external: true
